### ISSUE TITLE
[Feature Request] Intelligently run code based on file name

### ISSUE THREAD

**Issue by bag-man** [JarrodCTaylor/vim-shell-executor#9]
My ideal workflow for this plugin would allow me to mid development, select a function say, and use a hotkey to run that function (and surrounding code) based on the file name. So *.py would run `python selected text`. *.js would run `node selected text` etc.

**Comment by JarrodCTaylor** [comment]
I would be open to looking at a pull request if you want to take a shot at it. This would need to be a separate command from the existing `ExecuteBuffer` and `ExecuteSelction` as we would need to differentiate between using the first line of text to determine how to run the file and using some kind of a default configured by the user based on file type.
